### ISSUE TITLE
Text Tweaks To Announcement Message For Notification

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/PokeNav#111]
Regular raids -- time only
EX Raids - time and date
Show "ex-raid" in the notification

**Comment by bradders2000** [comment]
Can I also suggest that if posting an egg, the notification tells you when it hatches, either in number of minutes from now or an actual time. Knowing when it finishes (as it does now) is not all that useful. 
I hope you’ll also adjust the notification so it says the level of the egg - once you’ve got that bit sorted out - I understand it’s work in progress. 
So the notification could then look like...
“Lx at <gym> hatches in x minutes” or “Lx at <gym> hatches at xx:xx”
When boss is known it could say “<boss> raid at <gym> ends in x minutes” or <boss> raid at <gym> ends at xx:xx”
