### ISSUE TITLE
Egg artwork and commands to set egg, hatch and despawn time

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/PokeNav#12]
Mentioning an egg in the raid announcement will set an image of the egg instead of a boss.

Setting a hatch time remaining will set an egg if no boss is set and the raid despawn.

Ideas:

`$hatch 44` -- sets 44 minutes to hatch 1:29 minutes to despawn
`$despawn 33` -- sets hatch to 0, 0:33 minutes to despawn

**Comment by fortepc** [comment]
Idea: 

`$hatchset 44`  -- sets 44 minutes to hatch 1:29 minutes to despawn
`$despawnset 33` -- sets hatch to 0, 0:33 minutes to despawn
`$timerset 22` -- if the channel is labeled as an egg currently it treats it like a `$hatchset`, if it's currently a known raid boss it treats it like a `$despawnset`.
`$starttimeset 18` -- sets the raid start time to 18 minutes away. If the raid will still be an egg at that time it gives an error.
`$starttimeset 5:40pm` -- sets the raid's scheduled start time to 5:40pm

`$hatch` -- returns the time remaining until it hatches, as well as the specific time it will hatch
`$despawn` -- returns the timer remaining until it despawns, as well as the specific time it will despawn
`$timer` -- returns whatever the next timer to expire is. If the egg hasn't hatched yet it returns the egg's timer, if the egg has hatched, and there is a scheduled start time, it returns that, if the scheduled start time has passed, or there is no scheduled start time then it returns the despawn time.
`$starttime` -- returns the timer remaining until scheduled start time, as well as the specific scheduled start time

**Comment by dandesousa** [comment]
I like the suggestions; here are my thoughts:

- The convention of `$setting` for fetch and `$setting set` for modification is interesting and I'd be open to adopting it but need to think over how I feel about it. Right now the convention is `$setting value` for most settings and then `$settings-command` that shows all the setting values (one command to remember to see everything). 

I'm going to keep thinking above over but heres what I like and will try to incorporate regardless if I adopt the above convention:

- `$hatch`, `$despawn`, `$timer` can be combined into the existing command `$time` (`$tr` -- timer is also a reasonable alias) which already exists to provide all the known timers for the raid (just need to add the timestamps).
   - If concern is around length of the message, unknown or expired timers (hatch when the raid is hatched) can be omitted unless an argument is provided) -- good suggestion
   - It also allows shorter form set functions (`$hatch` instead of `$hatch set` since people usually do this on mobile my philosophy has always been less time typing the better)

The start time is a feature thats been brought up before. However, it doesn't do anything that $status can't do but communicates less information. If you are interested in discussing this more I have made a separate ticket to take the start time convo out of here https://github.com/PokeNavBot/PokeNav/issues/24
