### ISSUE TITLE
Have boss updated when screenshot of "duplicate" raid includes hatch info

### ISSUE THREAD

**Issue by cupkait** [PokeNavBot/PokeNav#126]
When the initial call-out is egg-only and someone subsequently posts a screenshot for the same gym including the raid boss, have the secondary call-out update the raid info to more current/accurate data.

**Comment by bradders2000** [comment]
Once the bot has received the updated raid boss info (either via screenshot or $boss), it should honour the server setting for outputting the $counters info into the raid’s dedicated channel.
