### ISSUE TITLE
Request: "Raids" command to list all currently active non-ex raids in brief summary

### ISSUE THREAD

**Issue by fortepc** [PokeNavBot/PokeNav#143]
It would be useful in some circumstances to be able to use some command, like `$raids` to be able to get a quick compact summary of the active raids in the server. 

One specifically where I would benefit, is some channels in our discord server are bridged to a FB messenger group chat, and it would be useful if they could use the command on their end of the discord bridge to see a list of what's in `#active-raids` since they don't actually have access to it.

**Comment by dandesousa** [comment]
$list-raids -- but does it for all raids in the current lobby -- thing it gets you what you want.

**Comment by fortepc** [comment]
Oh. I'm stupid :-P

**Comment by fortepc** [comment]
Here's what I want to do. our main communication chat channel has a bridge to a Facebook messenger chat, and it would be nice if the people on the other side of the bridge could see a list of raids since they don't have access to #active-raids

![](https://i.imgur.com/j2IKE9h.png)

**Comment by dandesousa** [comment]
So that should work if they are talking into the raid lobby, $list-raids shows all the raids in the raid lobby.

Other option is to use the app :)

**Comment by dandesousa** [comment]
Sorry for the delay on this -- its only restricted to it because the original request was to display all the raids in the lobby (for regional stuff)
