### ISSUE TITLE
Raids not being created

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/PokeNav#145]
https://cdn.discordapp.com/attachments/428658223243853834/489416217438715919/image0.png

**Comment by jordb22** [comment]
The time is covered on the screenshot. The bot wouldn’t be able to determine the time for the raid.

**Comment by KayTV** [comment]
it should auto time a couple hours if the time is covered. iphone X always covers the time is the egg is hatched

**Comment by dandesousa** [comment]
Right it should also have reacted which in this case it did not
