### ISSUE TITLE
Duplicate location (same address) stops automatically setting the location

### ISSUE THREAD

**Issue by Rhendak** [PokeNavBot/PokeNav#159]
There's a duplicate address known for this Gym, both are the exact same address. However on the pokemongomap.info, it shows only one known location in the list. The problem with this is that it prevents the bot from automatically setting the location when a screenshot of this gym is uploaded.

![image](https://user-images.githubusercontent.com/1855295/46254822-92640600-c495-11e8-8c8b-6b34e07bef26.png)
![image](https://user-images.githubusercontent.com/1855295/46254827-a90a5d00-c495-11e8-9efd-ac3acd5cbfb6.png)

**Comment by dandesousa** [comment]
fixed in the next update
