### ISSUE TITLE
Feature Request: Multi Region Support

### ISSUE THREAD

**Issue by fortepc** [PokeNavBot/PokeNav#40]
I'd like support for different regions inside the same server. Let me make additional reporting channels tied to a single category. The way I'd like to have it in my server is this

*Region 1 Category*
-> Region 1 General Chat
-> Region 1 Raid Reports & Discussion
-> Region 1 Active Raids
-> Region 1 Trade Request & Discussion
-> Region 1 Active Trades
*Region 2 Category*
-> Region 2 General Chat
-> Region 2 Raid Reports & Discussion
-> Region 2 Active Raids
-> Region 2 Trade Request & Discussion
-> Region 2 Active Trades

**Comment by dandesousa** [comment]
So after consolidating various requests from users, this will be version one of multiple region support:

- Feature in raid lobbies (server level opt-in) to delete messages not pertaining to raids (cleanup of raids message -- making it much more similar to active raids).
- Ability to make channels read only to users who have permission to view the lobby they were created in
- A re-written raid summary message at the top of the channel which is kept up to date like active raids / raid announcement with new members, etc.
- Active raids remains a server level raid summary (for now -- this should be largely unnecessary at the region level but it can be revisited in the future)

You can consolidate raid reports and list into a single channel and have discussion elsewhere if desired.
