### ISSUE TITLE
Foreign Language EX Timestamp Support

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/PokeNav#53]

**Comment by dandesousa** [comment]
![screenshot_20180705-112758](https://user-images.githubusercontent.com/3880281/42382648-fb44d52c-8102-11e8-89e9-5e3aaa7bbf7a.png)

**Comment by dragonslife** [comment]
![img-20180706-wa0006](https://user-images.githubusercontent.com/1855295/42387019-6ca6ef78-8141-11e8-8b63-8e06eb8c523e.jpg)
