### ISSUE TITLE
When reporting an Egg; Channel Name 

### ISSUE THREAD

**Issue by cykopat** [PokeNavBot/PokeNav#62]
Is it possible to name the channel tier1-5 or egg1-5 before it hatches? Then after the hatch rename is pokemon-xxx-xx

**Feedback received:** 
> It's hard to tell what tier eggs are from the small screenshot and there's no way of enlarging on my phone (that I know of). Anyway, the egg tier could be displayed? Even if it's in the $status portion, which is what I've been doing manually so people know.

**Comment by dandesousa** [comment]
Yes when I add support for better egg recognition I will certainly do this!
