### ISSUE TITLE
Support Pokemon names in Other Languages

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/PokeNav#76]

**Comment by emman31** [comment]
[pokemon_de.json.txt](https://github.com/PokeNavBot/PokeNav/files/2257427/pokemon_de.json.txt)

**Comment by emman31** [comment]
[pokemon_fr.json.txt](https://github.com/PokeNavBot/PokeNav/files/2257990/pokemon_fr.json.txt)
