### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by pookdeveloper** [PokeNavBot/PokeNav#99]
Hi, are you planning to upload the code? I am curious to know how the treatment of the image works or what library do you use?

Thanks

**Comment by dandesousa** [comment]
This is an issue tracking repository. PokeNav is closed source atm, no plans to make it available in the near term. I'll be revisiting this in the fall.

**Comment by dandesousa** [comment]
If you want to chat more about how the internals work I can do so in the discord. Its not a trade secret or anything.

**Comment by pookdeveloper** [comment]
Thanks I dont know how can I contact with you, because I wrote here, Thanks @dandesousa

**Comment by dandesousa** [comment]
the website linked has a link to the discord

**Comment by pookdeveloper** [comment]
i dont find you.. my user in discord is pookdeveloper
